export interface Category {
  id: string;
  name: string;
  order: number;
  description?: string;
}

export interface PortionVariant {
  label: string;
  price: number;
}

export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  categoryId: string;
  imageUrl: string;
  isAvailable: boolean;
  isFeatured?: boolean;
  spiceLevel?: number;
  tags?: string[];
  variants?: PortionVariant[];
  createdAt: string;
  updatedAt: string;
}

export interface DatabaseSchema {
  restaurant: {
    name: string;
    tagline: string;
    address: string;
    phone: string;
    hours: string;
    instagram?: string;
    facebook?: string;
  };
  users: Array<{
    email: string;
    name: string;
    passwordHash: string;
    role: 'kasir';
  }>;
  categories: Category[];
  items: MenuItem[];
}

const now = new Date().toISOString();

export const REAL_RESTAURANT_SEED: DatabaseSchema = {
  restaurant: {
    name: 'Resto Maeso Aji Barokah',
    tagline: 'Warung Olahan Sop, Asem-Asem, Nasi Gandul, Rawon & Aneka Bakaran Khas Pati',
    address: 'Gedong, Kedumulyo, Kec. Sukolilo, Kabupaten Pati, Jawa Tengah 59172',
    phone: '082143800818',
    hours: '08.00 - 21.00 WIB (Buka Setiap Hari)',
    instagram: '@maeso_ajiresto',
    facebook: 'Resto Maeso Aji Barokah',
  },
  users: [
    {
      email: 'kasir@maesoaji.com',
      name: 'Kasir Resto Maeso Aji Barokah',
      passwordHash: '$2b$10$8hNdRWC2t36j.wfXR3SOT.z/J6sNSMk7ZyUiIRZvVsBH0S4.zzhEG',
      role: 'kasir',
    },
  ],
  categories: [
    { id: 'cat_sop', name: 'Sop', order: 1, description: 'Aneka olahan sop sapi kuah kaldu rempah bening gurih, lengkap nasi + es teh' },
    { id: 'cat_asem', name: 'Asem', order: 2, description: 'Hidangan asem-asem sapi kuah asam manis pedas segar khas Pati, lengkap nasi + es teh' },
    { id: 'cat_gandul', name: 'Gandul', order: 3, description: 'Sajian Nasi Gandul khas Pati berkuah santan rempah gurih nikmat, lengkap es teh' },
    { id: 'cat_soto', name: 'Soto', order: 4, description: 'Soto kuah sedap kaya rempah aromatik, disajikan lengkap nasi + es teh' },
    { id: 'cat_rawon', name: 'Rawon', order: 5, description: 'Rawon daging & babat kuah kluwek hitam pekat mantap, lengkap nasi + es teh' },
    { id: 'cat_goreng_bakar', name: 'Menu Goreng & Bakar', order: 6, description: 'Pilihan aneka lauk bakar beraroma arang dan lauk goreng gurih renyah' },
    { id: 'cat_cemilan', name: 'Menu Cemilan', order: 7, description: 'Kudapan gurih renyah pendamping makan santai' },
    { id: 'cat_bakso', name: 'Bakso', order: 8, description: 'Bakso daging sapi kenyal berkuah kaldu gurih segar' },
    { id: 'cat_minuman', name: 'Minuman', order: 9, description: 'Minuman dingin segar, aneka jus buah murni, dan seduhan hangat' },
    { id: 'cat_rice_bowl', name: 'Rice Bowl', order: 10, description: 'Paket praktis rice bowl ayam lezat lengkap nasi + es teh' },
  ],
  items: [
    // --- SOP (8 items with small/large portion variants) ---
    {
      id: 'item_sop_kikil',
      name: 'Sop Kikil + Nasi + Es Teh',
      description: 'Sop kikil sapi empuk kenyal gurih dengan kuah kaldu rempah bening, disajikan lengkap dengan nasi putih dan es teh.',
      price: 20000,
      categoryId: 'cat_sop',
      imageUrl: 'https://images.unsplash.com/photo-1547928576-96541e263435?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Sop Sapi', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_sop_buntut',
      name: 'Sop Buntut + Nasi + Es Teh',
      description: 'Sop buntut sapi pilihan istimewa dengan kuah kaldu rempah bening gurih mantap, lengkap nasi dan es teh.',
      price: 30000,
      categoryId: 'cat_sop',
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: true,
      spiceLevel: 0,
      tags: ['Sop Sapi', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_sop_balungan',
      name: 'Sop Balungan + Nasi + Es Teh',
      description: 'Sop balungan sapi berkaldu gurih sedap khas rempah Nusantara, disajikan dengan nasi putih hangat dan es teh.',
      price: 20000,
      categoryId: 'cat_sop',
      imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Sop Sapi', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_sop_iga',
      name: 'Sop Iga + Nasi + Es Teh',
      description: 'Sop iga sapi berdaging empuk berkuah kaldu rempah lezat, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_sop',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: true,
      spiceLevel: 0,
      tags: ['Sop Sapi', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_sop_daging',
      name: 'Sop Daging + Nasi + Es Teh',
      description: 'Sop daging sapi empuk berkuah kaldu gurih segar, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_sop',
      imageUrl: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Sop Sapi', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_sop_tetelan',
      name: 'Sop Tetelan + Nasi + Es Teh',
      description: 'Sop tetelan sapi gurih berempah meresap, disajikan lengkap dengan nasi putih dan es teh.',
      price: 20000,
      categoryId: 'cat_sop',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Sop Sapi', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_sop_babat',
      name: 'Sop Babat + Nasi + Es Teh',
      description: 'Sop babat sapi bersih dan empuk berkuah kaldu nikmat, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_sop',
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Sop Sapi', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_sop_koyor',
      name: 'Sop Koyor + Nasi + Es Teh',
      description: 'Sop koyor urat sapi gurih kenyal berkuah kaldu segar, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_sop',
      imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Sop Sapi', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },

    // --- ASEM (8 items with small/large portion variants) ---
    {
      id: 'item_asem_kikil',
      name: 'Asem Kikil + Nasi + Es Teh',
      description: 'Asem-asem kikil sapi empuk dengan kuah asam gurih segar khas Pati, lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_asem',
      imageUrl: 'https://images.unsplash.com/photo-1547928576-96541e263435?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Asem-Asem', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_asem_buntut',
      name: 'Asem Buntut + Nasi + Es Teh',
      description: 'Asem-asem buntut sapi kuah asam pedas gurih segar meresap istimewa, lengkap nasi dan es teh.',
      price: 30000,
      categoryId: 'cat_asem',
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: true,
      spiceLevel: 1,
      tags: ['Asem-Asem', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_asem_balungan',
      name: 'Asem Balungan + Nasi + Es Teh',
      description: 'Asem-asem balungan sapi nikmat segar dengan potongan belimbing wuluh dan tomat, lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_asem',
      imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Asem-Asem', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_asem_iga',
      name: 'Asem Iga + Nasi + Es Teh',
      description: 'Asem-asem iga sapi berdaging empuk berbumbu asam pedas segar, lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_asem',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: true,
      spiceLevel: 1,
      tags: ['Asem-Asem', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_asem_daging',
      name: 'Asem Daging + Nasi + Es Teh',
      description: 'Asem-asem daging sapi empuk dengan kuah asam gurih segar bercitarasa khas, lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_asem',
      imageUrl: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Asem-Asem', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_asem_tetelan',
      name: 'Asem Tetelan + Nasi + Es Teh',
      description: 'Asem-asem tetelan sapi gurih berkuah asam pedas segar meresap, lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_asem',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Asem-Asem', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_asem_babat',
      name: 'Asem Babat + Nasi + Es Teh',
      description: 'Asem-asem babat sapi empuk dengan kuah asam gurih berempah, lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_asem',
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Asem-Asem', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_asem_koyor',
      name: 'Asem Koyor + Nasi + Es Teh',
      description: 'Asem-asem koyor urat sapi kenyal berkuah asam manis segar mantap, lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_asem',
      imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Asem-Asem', 'Paket Lengkap'],
      variants: [
        { label: 'Kecil', price: 20000 },
        { label: 'Besar', price: 30000 },
      ],
      createdAt: now,
      updatedAt: now,
    },

    // --- GANDUL (2 items, 30000 each) ---
    {
      id: 'item_gandul_daging',
      name: 'Gandul Daging + Nasi + Es Teh',
      description: 'Nasi Gandul khas Pati dengan irisan daging sapi empuk kuah santan rempah legit, disajikan lengkap dengan es teh.',
      price: 30000,
      categoryId: 'cat_gandul',
      imageUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Khas Pati', 'Nasi Gandul'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_gandul_campur',
      name: 'Gandul Campur + Nasi + Es Teh',
      description: 'Nasi Gandul khas Pati dengan isian campur daging dan aneka jeroan sapi gurih meresap, disajikan lengkap dengan es teh.',
      price: 30000,
      categoryId: 'cat_gandul',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Khas Pati', 'Nasi Gandul'],
      createdAt: now,
      updatedAt: now,
    },

    // --- SOTO (3 items, 20000 each) ---
    {
      id: 'item_soto_ayam',
      name: 'Soto Ayam + Nasi + Es Teh',
      description: 'Soto ayam suwir kuah kuning bening gurih segar kaya bumbu rempah, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_soto',
      imageUrl: 'https://images.unsplash.com/photo-1572656631137-7935297eff55?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Soto', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_soto_daging',
      name: 'Soto Daging + Nasi + Es Teh',
      description: 'Soto daging sapi empuk berkuah rempah sedap hangat, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_soto',
      imageUrl: 'https://images.unsplash.com/photo-1594998893017-36147cbcae05?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Soto', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_soto_babat',
      name: 'Soto Babat + Nasi + Es Teh',
      description: 'Soto babat sapi empuk berkuah kaldu gurih aromatik segar, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_soto',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Soto', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },

    // --- RAWON (2 items, 20000 each) ---
    {
      id: 'item_rawon_daging',
      name: 'Rawon Daging + Nasi + Es Teh',
      description: 'Rawon daging sapi kuah kluwek hitam pekat gurih sedap mantap, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_rawon',
      imageUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Rawon', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_rawon_babat',
      name: 'Rawon Babat + Nasi + Es Teh',
      description: 'Rawon babat sapi berkuah kluwek hitam rempah gurih, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_rawon',
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Rawon', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },

    // --- MENU GORENG & BAKAR (21 items) ---
    {
      id: 'item_nasgor_spesial',
      name: 'Nasi Goreng Spesial',
      description: 'Nasi goreng bumbu racik khas warung dengan telur gurih dan taburan bawang renyah.',
      price: 17000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Nasi Goreng'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_bebek_bakar',
      name: 'Bebek Bakar + Nasi + Es Teh',
      description: 'Bebek bakar bumbu kecap rempah meresap beraroma arang, lengkap nasi, sambal, lalapan, dan es teh.',
      price: 34000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Olahan Bakar', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_bebek_goreng',
      name: 'Bebek Goreng + Nasi + Es Teh',
      description: 'Bebek goreng empuk bumbu rempah gurih berbalut kremes, lengkap nasi, sambal, lalapan, dan es teh.',
      price: 31000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Olahan Goreng', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_ayam_bakar',
      name: 'Ayam Bakar + Nasi + Es Teh',
      description: 'Ayam bakar manis gurih beraroma bakaran arang, lengkap nasi, sambal, lalapan, dan es teh.',
      price: 32000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Olahan Bakar', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_ayam_goreng',
      name: 'Ayam Goreng + Nasi + Es Teh',
      description: 'Ayam goreng bumbu kuning empuk gurih meresap, lengkap nasi, sambal, lalapan, dan es teh.',
      price: 30000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Olahan Goreng', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_nila_bakar',
      name: 'Nila Bakar + Nasi + Es Teh',
      description: 'Ikan nila bakar bumbu rempah manis pedas gurih harum, lengkap nasi, lalapan, sambal, dan es teh.',
      price: 29000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Olahan Ikan', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_nila_goreng',
      name: 'Nila Goreng + Nasi + Es Teh',
      description: 'Ikan nila goreng renyah garing gurih bumbu rempah, lengkap nasi, sambal, lalapan, dan es teh.',
      price: 26000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Olahan Ikan', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_gurame_bakar',
      name: 'Gurame Bakar + Nasi + Es Teh',
      description: 'Ikan gurame bakar olesan bumbu spesial bakar sedap, disajikan lengkap nasi dan es teh.',
      price: 36000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Olahan Ikan', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_gurame_goreng',
      name: 'Gurame Goreng + Nasi + Es Teh',
      description: 'Ikan gurame goreng garing krispi bumbu bawang ketumbar, disajikan lengkap nasi dan es teh.',
      price: 33000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Olahan Ikan', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_lele_goreng',
      name: 'Lele Goreng + Nasi + Es Teh',
      description: 'Ikan lele goreng renyah bumbu bawang ketumbar gurih nikmat, disajikan lengkap nasi dan es teh.',
      price: 20000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 1,
      tags: ['Olahan Ikan', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_limpa_goreng',
      name: 'Limpa Goreng',
      description: 'Limpa sapi goreng bumbu bacem gurih legit mantap.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Jeroan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_ati_goreng',
      name: 'Ati Goreng',
      description: 'Ati sapi goreng empuk gurih berbumbu rempah meresap.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Jeroan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_ati_rempelo',
      name: 'Ati Rempelo',
      description: 'Ati rempelo / ampela goreng gurih renyah sedap.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Jeroan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_babat_goreng',
      name: 'Babat Goreng',
      description: 'Babat sapi goreng bumbu ungkep gurih empuk sedap.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Jeroan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_usus_goreng',
      name: 'Usus Goreng',
      description: 'Usus goreng garing gurih renyah berbumbu rempah.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Jeroan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_paru_goreng',
      name: 'Paru Goreng',
      description: 'Paru sapi goreng renyah gurih nikmat berempah.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Jeroan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_cingur_goreng',
      name: 'Cingur Goreng',
      description: 'Cingur sapi goreng kenyal gurih berbumbu rempah khas.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Jeroan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_kuping_goreng',
      name: 'Kuping Goreng',
      description: 'Kuping sapi goreng kenyal gurih berbumbu bacem sedap.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Jeroan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_otak_goreng',
      name: 'Otak Goreng',
      description: 'Otak sapi goreng gurih lembut berbalut bumbu sedap.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Jeroan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_kepala_ayam',
      name: 'Kepala Ayam',
      description: 'Kepala ayam ungkep bumbu kuning goreng gurih.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Unggas'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_kepala_bebek',
      name: 'Kepala Bebek',
      description: 'Kepala bebek ungkep bumbu rempah goreng gurih sedap.',
      price: 15000,
      categoryId: 'cat_goreng_bakar',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Olahan Unggas'],
      createdAt: now,
      updatedAt: now,
    },

    // --- MENU CEMILAN (3 items) ---
    {
      id: 'item_tahu_walik',
      name: 'Tahu Walik',
      description: 'Tahu walik goreng renyah isi gurih, nikmat disajikan dengan cabai rawit.',
      price: 10000,
      categoryId: 'cat_cemilan',
      imageUrl: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Cemilan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_sosis_nugget',
      name: 'Sosis + Nugget Goreng',
      description: 'Porsi sosis dan nugget goreng renyah hangat disajikan dengan saus cocolan.',
      price: 10000,
      categoryId: 'cat_cemilan',
      imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Cemilan'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_kentang_goreng',
      name: 'Kentang Goreng',
      description: 'Kentang goreng stik renyah gurih bertabur garam gurih hangat.',
      price: 10000,
      categoryId: 'cat_cemilan',
      imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Cemilan'],
      createdAt: now,
      updatedAt: now,
    },

    // --- BAKSO (6 items) ---
    {
      id: 'item_bakso_biasa',
      name: 'Bakso Biasa',
      description: 'Bakso sapi halus kenyal berkuah kaldu segar dengan mie dan sayur.',
      price: 13000,
      categoryId: 'cat_bakso',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Bakso Sapi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_bakso_kosongan',
      name: 'Bakso Kosongan',
      description: 'Porsi bakso daging sapi tanpa mie dalam kuah kaldu sapi gurih segar.',
      price: 13000,
      categoryId: 'cat_bakso',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Bakso Sapi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_bakso_tetelan',
      name: 'Bakso Tetelan',
      description: 'Bakso sapi kuah kaldu gurih dengan limpahan tetelan sapi empuk nikmat.',
      price: 20000,
      categoryId: 'cat_bakso',
      imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Bakso Sapi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_bakso_balungan',
      name: 'Bakso Balungan',
      description: 'Bakso sapi spesial dengan balungan sapi berkaldu gurih sedap mantap.',
      price: 20000,
      categoryId: 'cat_bakso',
      imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Bakso Sapi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_bakso_babat',
      name: 'Bakso Babat',
      description: 'Bakso sapi disajikan dengan potongan babat sapi empuk berkaldu gurih.',
      price: 20000,
      categoryId: 'cat_bakso',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Bakso Sapi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_bakso_urat',
      name: 'Bakso Urat',
      description: 'Bakso sapi urat kenyal mantap bertekstur nikmat dalam kuah kaldu gurih.',
      price: 20000,
      categoryId: 'cat_bakso',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Bakso Sapi'],
      createdAt: now,
      updatedAt: now,
    },

    // --- MINUMAN (25 items) ---
    {
      id: 'item_es_teh',
      name: 'Es Teh',
      description: 'Teh seduh manis disajikan dingin segar dengan es batu kristal.',
      price: 3000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Dingin'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_es_sirup',
      name: 'Es Sirup',
      description: 'Minuman sirup manis dingin pelepas dahaga.',
      price: 3000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Dingin'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_es_jeruk',
      name: 'Es Jeruk',
      description: 'Perasan jeruk asli manis segar disajikan dingin dengan es batu.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Dingin'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_es_lemon_tea',
      name: 'Es Lemon Tea',
      description: 'Seduhan teh segar dipadu perasan sari lemon dingin menyegarkan.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Dingin'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_es_susu',
      name: 'Es Susu',
      description: 'Susu manis disajikan dingin menyegarkan dan bernutrisi.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Dingin'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_es_white_coffee',
      name: 'Es White Coffee',
      description: 'Kopi putih creamy disajikan dingin mantap melegakan dahaga.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Kopi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_es_jahe',
      name: 'Es Jahe',
      description: 'Seduhan air jahe asli wangi dipadu kesegaran es dingin.',
      price: 8000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Tradisional'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_es_buah',
      name: 'Es Buah',
      description: 'Kombinasi aneka buah segar dengan sirup manis dan susu segar.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Dingin'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_es_nutrisari',
      name: 'Es Nutrisari',
      description: 'Minuman sari buah jeruk manis dingin pelepas dahaga.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Dingin'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jahe_anget',
      name: 'Jahe Anget',
      description: 'Seduhan jahe murni hangat berkhasiat menghangatkan tubuh.',
      price: 3000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Hangat'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_teh_anget',
      name: 'Teh Anget',
      description: 'Teh manis hangat dengan aroma melati alami khas warung.',
      price: 3000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Hangat'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jeruk_anget',
      name: 'Jeruk Anget',
      description: 'Perasan jeruk asli hangat manis alami melegakan tenggorokan.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Minuman Hangat'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_kopi_hitam',
      name: 'Kopi Hitam',
      description: 'Kopi hitam tubruk mantap khas warung nusantara.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Kopi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_es_kopi',
      name: 'Es Kopi',
      description: 'Kopi hitam racik disajikan dingin segar penambah semangat.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Kopi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_cappucino',
      name: 'Cappucino',
      description: 'Kopi cappucino berbusa lembut gurih dan creamy.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Kopi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_good_day',
      name: 'Good Day',
      description: 'Kopi Good Day seduh aneka rasa manis nikmat.',
      price: 5000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Kopi'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jus_jambu',
      name: 'Jus Jambu',
      description: 'Jus jambu biji merah segar kaya vitamin dan serat alami.',
      price: 7000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Jus Buah'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jus_buah_naga',
      name: 'Jus Buah Naga',
      description: 'Jus buah naga merah kental manis segar alami.',
      price: 8000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Jus Buah'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jus_melon',
      name: 'Jus Melon',
      description: 'Jus buah melon manis segar dingin menyegarkan tubuh.',
      price: 7000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Jus Buah'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jus_jeruk',
      name: 'Jus Jeruk',
      description: 'Jus perasan jeruk murni dingin kaya vitamin C.',
      price: 7000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Jus Buah'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jus_alpukat',
      name: 'Jus Alpukat',
      description: 'Jus alpukat mentega kental legit dengan kucuran susu cokelat.',
      price: 9000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Jus Buah'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jus_wortel',
      name: 'Jus Wortel',
      description: 'Jus wortel segar bernutrisi tinggi menyehatkan tubuh.',
      price: 7000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Jus Buah'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jus_tomat',
      name: 'Jus Tomat',
      description: 'Jus tomat merah segar kaya vitamin C dan antioksidan alami.',
      price: 7000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Jus Buah'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jus_sirsat',
      name: 'Jus Sirsat',
      description: 'Jus buah sirsak asam manis segar dingin alami.',
      price: 8000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Jus Buah'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_jus_nanas',
      name: 'Jus Nanas',
      description: 'Jus nanas madu manis segar dingin melegakan dahaga.',
      price: 7000,
      categoryId: 'cat_minuman',
      imageUrl: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Jus Buah'],
      createdAt: now,
      updatedAt: now,
    },

    // --- RICE BOWL (2 items, 13000 each) ---
    {
      id: 'item_bowl_chicken_katsu',
      name: 'Chicken Katsu + Nasi + Es Teh',
      description: 'Rice bowl ayam katsu krispi saus gurih, disajikan dengan nasi hangat dan es teh.',
      price: 13000,
      categoryId: 'cat_rice_bowl',
      imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Rice Bowl', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'item_bowl_chicken',
      name: 'Chicken + Nasi + Es Teh',
      description: 'Rice bowl olahan daging ayam lezat, disajikan dengan nasi putih dan es teh.',
      price: 13000,
      categoryId: 'cat_rice_bowl',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
      isAvailable: true,
      isFeatured: false,
      spiceLevel: 0,
      tags: ['Rice Bowl', 'Paket Lengkap'],
      createdAt: now,
      updatedAt: now,
    },
  ],
};
